config/routes.rb
Tvshows::Application.routes.draw do
  resources :authentications, :only => [:create, :destroy]

  devise_for :users, :path_names => { :sign_up => "register",
                                      :sign_in => "login",
                                      :sign_out => "logout" },
             :controllers => {
                                :registrations => 'registrations',
                                :sessions => 'sessions',
                                :omniauth_callbacks => "omniauth_callbacks"
                             } do
    
    get "users/cancel_omniauth", :to => "registrations#cancel_omniauth", :as => "cancel_omniauth"
    
    get "sessions/load_activities", :to => "sessions#load_activities"
    get "auth/failure", :to => "sessions#new", :as => "auth_failure"

    root :to => "sessions#index"
  end      

  resources :actors, :only => [:show]
  resources :seasons, :only => [:comment] do
    member do
      post  :comment
      get   :get_poster
      get   :mark
    end
  end
  resources :episodes, :only => [] do
    member do
      post :comment
      get  :get_poster
      get :mark
      get :unmark
      post :rate
    end
  end
  resources :shows, :only => [:index, :show] do
    resources :actors, :only => [:show, :index], :controller => "roles"
    collection do
      post :search
      get :search
      get :name
      get :popular
    end
    member do
      get :add  
      get :follow
      get :unfollow
      post :comment
      get :get_poster
      get :get_seasons
      get :get_next_episode
    end
    match "/season/:season_number" => "seasons#show", :constraints => { :season_number => /\d+/ }, :as => "season"
    match "/:season_number/:episode_number" => "episodes#show", :constraints => { :season_number => /\d+/, :episode_number => /\d+/ }, :as => "season_episode"
  end
  resources :genres, :only => [:show, :index]
  resources :users, :only => [:show, :index] do
    collection do
      get :name
    end
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :block
      get :unblock
    end
  end
  resources :comments, :only => [] do
    member do
      get :like
      get :unlike
      get :dislike
      get :undislike
    end
  end
  
  namespace "my" do
    resources :shows, :only => [:index, :show]
  end
  
  match '/robots.txt', :controller => :application, :action => :robots

  root :to => "sessions#index"

end

app/models/season.rb
class Season < ActiveRecord::Base
  include HasPoster
  has_attached_file :poster, {
                    :styles => { :medium => "200x289>", :small => "150x217>" },
                    :default_url => "/images/season_default_image.png"
                  }.merge(Tvshows::Application.config.paperclip_options)
  process_in_background :poster
  has_many :episodes, :dependent => :destroy, :order => "number ASC"
  belongs_to :series
  has_many :comments, :as => :commentable, :order => "created_at desc"
  
  attr_reader :poster_url
  after_save :attach_poster
  
  def attach_poster
    Delayed::Job.enqueue(AttachPosterToSeasonJob.new(id, @poster_url), { :priority => 2 }) unless @poster_url.nil?
  end
  
  def poster_url=(value)
    @poster_url = value
    self.poster_processing = !value.blank?
  end
  
  def full_name
    @full_name ||= "#{series.full_name} S#{number.to_s.rjust(2, '0')}"
  end
  
  def episodes_count
    episodes.size
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_filter :authenticate_user!, :only => [:comment, :mark]
  
  def show
    @season = Season.find_by_series_id_and_number(Series.find(params[:show_id]), params[:season_number])
    
    respond_to do |format|
      format.json { render :json => @season }
      format.html
    end
  end

  def comment
    if user_signed_in?
      @season = Season.find(params[:id])
      @comment = @season.comments.build(:content => params[:comment][:content],
                                 :user => current_user) 
      save_comment(@comment)
      a = current_user.activities.create!(:actor_path => user_path(current_user),
                                          :actor_img => current_user.avatar_url(:thumb),
                                          :subject => @comment,
                                          :subject_path => show_season_path(:show_id => @season.series, :season_number => @season.number, :anchor => "comment-#{@comment.id}"),
                                          :kind => "comment",
                                          :data => { "content" => @comment.content,
                                                    "commented_name" => @comment.commentable.full_name,
                                                    "commented_path" => show_season_path(:show_id => @season.series, :season_number => @season.number) }.to_json)
    end
  end
  
  def get_poster
    @season = Season.find(params[:id])
    respond_to do |format|
      format.js do
        if @season.poster_processing?
          render :nothing => true, :status => 403
        else
          if params[:size] == "small"
            render :partial => "poster_small", :locals => { :season => @season }
          else
            render :partial => "poster", :locals => { :season => @season }
          end
        end
      end
      format.html { redirect_to show_path(@season) } # redirect to show
    end
  end
  
  def mark
    season = Season.find(params[:id])
    current_user.episodes_seen << season.episodes
    respond_to do |format|
      format.js { render :partial => "shows/season_my", :locals => { :season => season } }
      format.html { redirect_to show_path(season.series) }
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_poster.html.erb
<% if season.poster_processing? %>
  <div class="processing" id="poster">
    <%= image_tag "ajax-loader-2.gif" %>
  </div>
<% else %>
  <div id="poster">
    <%= image_tag(season.poster.url(:medium), :class => "poster") %>
  </div>
<% end %>

app/views/seasons/_poster_small.html.erb
<% if season.poster_processing? %>
  <p id="season_poster_<%= season.id %>" class="processing">
    <%= link_to image_tag("ajax-loader-2.gif"), 
                show_season_path(:show_id => season.series, :season_number => season.number) %>
    <script type="text/javascript">

      $(document).ready(function(){
        var posterId = "season_poster_<%= season.id %>";
        var getPosterSeasonPath = "<%= get_poster_season_path(season, :size => 'small') %>";
        updateProcessingElements(null, "#" + posterId + ".processing", getPosterSeasonPath);
      });

    </script>
  </p>
<% else %>
  <p id="season_poster_<%= season.id %>">
    <%= link_to image_tag(season.poster.url(:small), :style => "border: 1px solid #DEDEDE;"), 
                show_season_path(:show_id => season.series, :season_number => season.number) %>
  </p>
<% end %>

app/views/seasons/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    var getPosterSeasonPath = "<%= get_poster_season_path(@season) %>";
    updateProcessingElements(null, "#poster.processing", getPosterSeasonPath);
  });
</script>
<div class="left_articles">
  <h2>
    <%= link_to "#{@season.series.name}", show_path(@season.series) %> <%= "S#{@season.number.to_s.rjust(2, "0")}" %>
  </h2>
  <p class="description">
	  <%= pluralize(@season.episodes.size, "episode") %>
	</p>
	<div id="seasons-<%= @season.id %>" class="season_info">
  	<div>
  	  <%= render :partial => "poster", :locals => { :season => @season } %>
  	  <div class="episodes-list">
        <% for episode in @season.episodes %>
        	<span id="episode-<%= episode.id %>" class="episode_info">
        	  <%= link_to "S#{@season.number.to_s.rjust(2, "0")}E#{episode.number.to_s.rjust(2, "0")} #{episode.name}",
        	              show_season_episode_path(:show_id => @season.series, :episode_number => episode.number,
        	              :season_number => @season.number) %>
        	</span>
        <% end %>
      </div>
      <div class="clear"></div>
  	</div>
	</div>
</div>

<%= render :partial => "shared/comments", :locals => { :comment_path => comment_season_path(@season), :comments => @season.comments } %>