config/routes.rb
Tvshows::Application.routes.draw do
  resources :authentications, :only => [:create, :destroy]

  devise_for :users, :path_names => { :sign_up => "register",
                                      :sign_in => "login",
                                      :sign_out => "logout" },
             :controllers => {
                                :registrations => 'registrations',
                                :sessions => 'sessions',
                                :omniauth_callbacks => "omniauth_callbacks"
                             } do
    
    get "users/cancel_omniauth", :to => "registrations#cancel_omniauth", :as => "cancel_omniauth"
    
    get "sessions/load_activities", :to => "sessions#load_activities"
    get "auth/failure", :to => "sessions#new", :as => "auth_failure"

    root :to => "sessions#index"
  end      

  resources :actors, :only => [:show]
  resources :seasons, :only => [:comment] do
    member do
      post  :comment
      get   :get_poster
      get   :mark
    end
  end
  resources :episodes, :only => [] do
    member do
      post :comment
      get  :get_poster
      get :mark
      get :unmark
      post :rate
    end
  end
  resources :shows, :only => [:index, :show] do
    resources :actors, :only => [:show, :index], :controller => "roles"
    collection do
      post :search
      get :search
      get :name
      get :popular
    end
    member do
      get :add  
      get :follow
      get :unfollow
      post :comment
      get :get_poster
      get :get_seasons
      get :get_next_episode
    end
    match "/season/:season_number" => "seasons#show", :constraints => { :season_number => /\d+/ }, :as => "season"
    match "/:season_number/:episode_number" => "episodes#show", :constraints => { :season_number => /\d+/, :episode_number => /\d+/ }, :as => "season_episode"
  end
  resources :genres, :only => [:show, :index]
  resources :users, :only => [:show, :index] do
    collection do
      get :name
    end
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :block
      get :unblock
    end
  end
  resources :comments, :only => [] do
    member do
      get :like
      get :unlike
      get :dislike
      get :undislike
    end
  end
  
  namespace "my" do
    resources :shows, :only => [:index, :show]
  end
  
  match '/robots.txt', :controller => :application, :action => :robots

  root :to => "sessions#index"

end

app/controllers/my/shows_controller.rb
class My::ShowsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @shows = current_user.series.order("name ASC") if current_user
  end
  
  def show
    @show = Series.find(params[:id])
    @unseen_episodes = @show.episodes.available.unseen_by(current_user)
    @next_episode = @show.next_episode
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  require 'net/http'
  
  before_filter :authenticate_user!, :only => [ :my, :subscribe, :unsubscribe ]
  
  public
  
  def index
    name_alpha
    render :action => :name
  end
  
  def search
    if request.xhr?
      results = { :query => params[:query], :suggestions => [], :data => [] }
      query = params[:query].downcase.strip
      unless query.starts_with?("the ")
        series = Series.where("lower(name) LIKE :name OR lower(name_prefix) LIKE :name", { :name => "%#{query}%"} ).all
      else
        series = Series.where("(lower(name_prefix) = 'the' AND lower(name) LIKE :name_sub) OR (lower(name) LIKE :name)", { :name => "%#{query}%", :name_sub => "%#{query.gsub(/^the\s/, '')}%"} ).all
      end
      series.each do |serie|
        results[:suggestions] << serie.full_name
        results[:data] << { :id => serie.id, :param => serie.to_param } 
      end
      results[:suggestions] << "#{params[:query]}"
      results[:data] << { :param => "search?q=#{params[:query]}"}
      render :json => results.to_json
    else
      tvdb = TvdbParty::Search.new(Tvshows::Application.config.the_tv_db_api_key)
      results = tvdb.search(params[:q])
      db_series = Series.where("lower(name) LIKE lower(:name)", { :name => "%#{params[:q]}%" }).all
      @series = []
      
      
      respond_to do |format|
        format.html do
          results.each do |s|
            unless s["Overview"].blank?
              db_serie = db_series.detect { |ds| ds.series_id == s["seriesid"].to_i }
              if db_serie.nil?
                s["Link"] = add_show_path(s["seriesid"])
                s["Saved"] = false
              else
                s["Link"] = show_path(db_serie)
                s["Saved"] = true
              end
              @series << s
            end
          end
          redirect_to @series.first["Link"] if @series.size == 1 && @series.first["Saved"]
        end #search.html.erb
        format.json do
          results.each do |s|
            unless s["Overview"].blank?
              db_serie = db_series.detect { |ds| ds.series_id == s["seriesid"].to_i }
              s["Link"] = db_serie.nil? ? add_show_path(s["seriesid"], :format => :json) : show_path(db_serie, :format => :json)
              @series << s
            end
          end 
          render :json => @series
        end
      end
    end
  end
  
  def show
    @series = Series.find(params[:id])

    if user_signed_in?
      # A logged user can comment
      @comment = Comment.new
      
      # If the user is watching this show
      if current_user.watch?(@series)
        # Get the next episode unseen
        @unseen_episodes = @series.episodes.available.unseen_by(current_user)
        @next_episode_unseen = @unseen_episodes.first

        # Display the activity tab
        if params[:tab].nil?
          redirect_to show_path(@series, :tab => "activity")
          return
        end
      end
    end

    @page_title = @series.full_name
    respond_to do |format|
      format.json { render :json => @series.as_json }
      format.html
    end
  end
  
  def add
    series = Series.where(:series_id => params[:id]).first
    if series.nil?
      tvdb = TvdbParty::Search.new(Tvshows::Application.config.the_tv_db_api_key)
      s = tvdb.get_series_by_id(params[:id])
      series = Series.new(:name => s.name, :series_id => s.id,
                          :tvdb_id => s.tvdb_id, :description => s.overview,
                          :first_aired => s.first_aired, :network => s.network,
                          :rating => s.rating, :runtime => s.runtime,
                          :status => s.status == "Continuing",
                          :imdb_id => s.imdb_id,
                          :rating_count => s.rating_count,
                          :air_time => s.air_time, :air_day => s.air_day,
                          :seasons_processing => true, :poster_url => s.poster)
      s.genres.each { |genre| series.genres << Genre.find_or_initialize_by_name(genre) }
      if !series.save
        redirect_to root_url, :notice => "Sorry, there was a problem saving the TV show #{series.full_name}. Try again later."
        return
      end
    end
    
    redirect_to show_path(series)
  end
  
  def follow
    @series = Series.find(params[:id])
    if current_user.following?(@series)
      respond_to do |format|
        format.js   # render follow.js.erb
        format.html { redirect_to show_path(@series) }
      end
    else
      fw = current_user.follow(@series)
      a = current_user.activities.create!(:actor_path => user_path(current_user),
                                          :actor_img => current_user.avatar_url(:thumb),
                                          :subject => fw,
                                          :kind => "follow_serie",
                                          :data => { "serie_path" => show_path(@series),
                                                    "serie_name" => @series.full_name,
                                                    "serie_img" => @series.poster.url(:thumb),
                                                    "serie_desc" => @series.description }.to_json)
      respond_to do |format|
        format.js   # render follow.js.erb
        format.html { redirect_to show_path(@series), :notice => "You are now following #{@series.full_name}" }
      end
    end
  end
  
  def unfollow
    @series = Series.find(params[:id])
    if current_user.following?(@series)
      current_user.stop_following(@series)
      respond_to do |format|
        format.js   # render unsubscribe.js.erb
        format.html { redirect_to show_path(@series), :notice => "You are not following #{@series.name} anymore." }
      end
    else
      respond_to do |format|
        format.js   # render unsubscribe.js.erb
        format.html { redirect_to show_path(@series) }
      end
    end
  end
  
  def actors
  end
  
  def comment
    if user_signed_in?
      @series = Series.find(params[:id])
      @comment = @series.comments.build(:content => params[:comment][:content],
                                 :user => current_user) 
      save_comment(@comment)
      a = current_user.activities.create!(:actor_path => user_path(current_user),
                                          :actor_img => current_user.avatar_url(:thumb),
                                          :subject => @comment,
                                          :subject_path => show_path(@series, :anchor => "comment-#{@comment.id}"),
                                          :kind => "comment",
                                          :data => { "content" => @comment.content,
                                                    "commented_name" => @comment.commentable.full_name,
                                                    "commented_path" => show_path(@series) }.to_json)
    end
  end
  
  def name
    name_alpha
  end
  
  def get_poster
    @series = Series.find(params[:id])
    respond_to do |format|
      format.js do
        if @series.poster_processing?
          render :nothing => true, :status => 403
        else
          render :partial => "poster", :locals => { :series => @series }
        end
      end
      format.html { redirect_to show_path(@series) } # redirect to show
    end
  end
  
  def popular
  end
  
  def get_seasons
    @series = Series.find(params[:id])
    respond_to do |format|
      format.js do
        if @series.seasons_processing?
          render :nothing => true, :status => 403
        else
          render :partial => "seasons", :locals => { :series => @series.seasons }
        end
      end
      format.html { redirect_to show_path(@series) } # redirect to show
    end
  end
  
  def genres
    @genres = Genre
  end
  
  def get_next_episode
    series = Series.find(params[:id])
    if current_user.watch?(series)
      # Get the next episode unseen
      unseen_episodes = series.episodes.available.unseen_by(current_user)
      @next_episode_unseen = unseen_episodes.first

      respond_to do |format|
        format.js { render :partial => "shows/next_episode_my" }
      end
    end
  end
  
  private
  def name_alpha
    if params[:letter].nil?
      @series = Series.where("name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? \
                              OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ?",
                              "0%", "1%", "2%", "3%", "4%", "5%", "6%", "7%", "8%", "9%")
    elsif ('A'..'Z').include?(params[:letter])
      @series = Series.where("name LIKE ?", "#{params[:letter]}%").order("name asc")
    else
      @series = []
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper

  def az_shows_initials(current_letter)
    content = ""
    ('A'..'Z').each do |l|
      content << "<li"
      content << " class=\"selected\"" if current_letter == l
      content << ">" + (link_to l, name_shows_path(:letter => l)) + '</li>'
    end
    
    content.html_safe
  end
  
  def people_watching(serie)
    people_watching = serie.watchers.all
    
    if people_watching.size.zero?
      desc = "Nobody is watching this TV show"
    elsif user_signed_in?
      watchers = []
    
      # Put the current user in the watchers list if he watches the serie
      if people_watching.include?(current_user) 
        watchers << "You"
        people_watching = people_watching - [current_user]
      end
      
      followings_watching = current_user.followings_watching(serie)
      
      # Do not display more than 3 friends in the description
      if followings_watching.size > 3
        # If there are more than 3 friends put a number of friends !
        watchers << "#{followings_watching.size} of your friends"
      else
        # Otherwise, lists the friends
        followings_watching.each { |f| watchers << link_to(f.username, user_path(f)) ; people_watching.delete(f) } unless followings_watching.size.zero?
      end

      # Remove friends from anonymous people
      people_watching = people_watching - followings_watching
      
      # Finally, put the rest of the watchers (anonymous)
      if watchers.size.zero?
        watchers << "#{pluralize(people_watching.size, 'person is', 'people are')}"
        desc = "#{watchers.to_sentence} watching this show"
      else
        watchers << "#{pluralize(people_watching.size, 'other person', 'other people')}" unless people_watching.size.zero?
        desc = "#{watchers.to_sentence} " + (serie.watchers.size == 1 && serie.watchers.first != current_user ? "is" : "are") + " watching this show"
      end
    else
      desc = "#{pluralize(people_watching.size, 'person is', 'people are')} watching this TV show"
    end
    desc.html_safe
  end
  
  def people_watching_except_you(serie)
    people_watching = serie.watchers.all.reject{|u| u == current_user}
    if people_watching.size.zero?
      desc = "Nobody else is watching this TV show"
    elsif user_signed_in?
      watchers = []
      
      followings_watching = current_user.followings_watching(serie)
      
      # Do not display more than 3 friends in the description
      if followings_watching.size > 3
        # If there are more than 3 friends put a number of friends !
        watchers << "#{followings_watching.size} of your friends"
      else
        # Otherwise, lists the friends
        followings_watching.each { |f| watchers << link_to(f.username, user_path(f)) ; people_watching.delete(f) } unless followings_watching.size.zero?
      end

      # Remove friends from anonymous people
      people_watching = people_watching - followings_watching
      
      # Finally, put the rest of the watchers (anonymous)
      if watchers.size.zero?
        watchers << "#{pluralize(people_watching.size, 'person is', 'people are')}"
        desc = "#{watchers.to_sentence} watching this show"
      else
        watchers << "#{pluralize(people_watching.size, 'other person', 'other people')}" unless people_watching.size.zero?
        desc = "#{watchers.to_sentence} " + (serie.watchers.reject{|w| w == current_user}.size == 1 ? "is" : "are") + " watching this show"
      end
    else
      desc = "#{pluralize(people_watching.size, 'person is', 'people are')} watching this TV show"
    end
    desc.html_safe
  end
  
  def watch_button(series)
    if user_signed_in?
      if current_user.watch?(series)
        link_to "Unfollow", unfollow_show_path(series), :class => "rm-movie-icon"
      else
        link_to "Follow", follow_show_path(series), :class => "add-movie-icon"
      end
    else
      "&nbsp;".html_safe
    end
  end
end

app/views/my/shows/index.html.erb
<%= render "shows/series_categories" %>
<% for show in @shows %>
<div class="left_articles">
	<div id="series_info">
	  <h2><%= link_to show.full_name, my_show_path(show) %></h2>
  	<p class="description">
  	  <%= people_watching_except_you(show) %>
  	</p>
  	<p>
      <%= image_tag show.poster.url(:small), :class => "thumbnail" %>
      <div id="latest_episodes_<%= show.id %>">
        <p class="title">Last episodes:</p>
        <div class="latest_episodes">
          <% show.episodes.available.last(3).each do |episode| %>
            <div class="last_episode">
              <%= link_to (image_tag(episode.poster.url(:small)) + content_tag(:span, episode.full_name, :style => "display:block")),
                          show_season_episode_path(:show_id => episode.series, :season_number => episode.season.number, :episode_number => episode.number) %>
            </div>
          <% end %>
          <div class="clear"></div>
        </div>
      </div>
  	</p>
  	<div style="clear:both"></div>
  </div>
</div>
<% end %>

app/views/my/shows/show.html.erb
<style>
  .left_articles .title { font-weight:bold; }
  .season_info .episode_info { width:450px; }
</style>
<div class="left_articles">
	<div id="series_info">
	  <h2><%= link_to @show.full_name %></h2>
  	<p class="description">
  	  <%= people_watching_except_you(@show) %>
  	</p>
  	<div>
      <%= image_tag @show.poster.url(:small), :class => "thumbnail" %>
      <div id="latest_episodes">
        <p class="title">Last episodes unseen (<%= "#{@unseen_episodes.size}/#{@show.episodes.available.size}" %>):</p>
        <div class="latest_episodes">
          <% @unseen_episodes.last(3).each do |episode| %>
            <div class="last_episode">
              <%= link_to (image_tag(episode.poster.url(:small)) + content_tag(:span, episode.full_name + " (" + (l episode.first_aired, :format => :dmy_with_long_month) + ")", :style => "display:block")),
                          show_season_episode_path(:show_id => episode.series, :season_number => episode.season.number, :episode_number => episode.number) %>
            </div>
          <% end %>
          <div class="clear"></div>
        </div>
      </div>
      <% if @show.next_episode %>
      <div id="new_episode">
        <p style="text-align:left;">
          <span class="title">Next episode:</span><br />
          <% if @next_episode.poster.file? %>
          <%= (link_to (image_tag @next_episode.poster.url(:thumb)) + content_tag(:span, @show.next_episode.full_name, :style => "display:block"),
                       show_season_episode_path(:show_id => @show,
                                                :season_number => @next_episode.season.number,
                                                :episode_number => @next_episode.number)) %>
          <% else %>
          <%= link_to @next_episode.full_name, show_season_episode_path(:show_id => @show, :season_number => @next_episode.season.number, :episode_number => @next_episode.number) %>
          <br />
          <% end %>
           on <%= (l @show.next_episode.first_aired, :format => :dmy_with_long_month ) %>
           at <%= @show.air_time %>
        </p>
      </div>
      <% end %>
      <div id="unseen_episodes" style="border-top:1px solid #CCC;margin-top:20px;padding-top:20px">
        <% for season in @show.seasons %>
          <div id="season_<%= season.number %>" class="season_info" style>
            <p style="background-color:#CCC;border:1px solid black;padding:5px;text-align:center" class="title">Season <%= season.number%></p>
            <p>
            <% for episode in season.episodes.available %>
            	<p id="episode-<%= episode.id %>" class="episode_info">
            	  <%= image_tag episode.poster.url(:small), :class => "thumbnail" %>
                <span style="display:inline-block;">
                  Aired on: <%= (l episode.first_aired, :format => :dmy_with_long_month ) %><br />
            	  </span>
            	  <br class="clear" />
                <%= check_box_tag "check_episode_#{episode.id}" %>
            	  <%= link_to episode.full_name,
          	              show_season_episode_path(:show_id => @show, :episode_number => episode.number,
          	              :season_number => episode.season.number), :style => "display:inline-block;" %>
            	</p>
            <% end %>
            </p>
            <div class="clear"></div>
          </div>
        <% end%>
      </div>
  	</div>
  </div>
</div>