config/routes.rb
Tvshows::Application.routes.draw do
  resources :authentications, :only => [:create, :destroy]

  devise_for :users, :path_names => { :sign_up => "register",
                                      :sign_in => "login",
                                      :sign_out => "logout" },
             :controllers => {
                                :registrations => 'registrations',
                                :sessions => 'sessions',
                                :omniauth_callbacks => "omniauth_callbacks"
                             } do
    
    get "users/cancel_omniauth", :to => "registrations#cancel_omniauth", :as => "cancel_omniauth"
    
    get "sessions/load_activities", :to => "sessions#load_activities"
    get "auth/failure", :to => "sessions#new", :as => "auth_failure"

    root :to => "sessions#index"
  end      

  resources :actors, :only => [:show]
  resources :seasons, :only => [:comment] do
    member do
      post  :comment
      get   :get_poster
      get   :mark
    end
  end
  resources :episodes, :only => [] do
    member do
      post :comment
      get  :get_poster
      get :mark
      get :unmark
      post :rate
    end
  end
  resources :shows, :only => [:index, :show] do
    resources :actors, :only => [:show, :index], :controller => "roles"
    collection do
      post :search
      get :search
      get :name
      get :popular
    end
    member do
      get :add  
      get :follow
      get :unfollow
      post :comment
      get :get_poster
      get :get_seasons
      get :get_next_episode
    end
    match "/season/:season_number" => "seasons#show", :constraints => { :season_number => /\d+/ }, :as => "season"
    match "/:season_number/:episode_number" => "episodes#show", :constraints => { :season_number => /\d+/, :episode_number => /\d+/ }, :as => "season_episode"
  end
  resources :genres, :only => [:show, :index]
  resources :users, :only => [:show, :index] do
    collection do
      get :name
    end
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :block
      get :unblock
    end
  end
  resources :comments, :only => [] do
    member do
      get :like
      get :unlike
      get :dislike
      get :undislike
    end
  end
  
  namespace "my" do
    resources :shows, :only => [:index, :show]
  end
  
  match '/robots.txt', :controller => :application, :action => :robots

  root :to => "sessions#index"

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  include ActiveModel::Serializers::JSON
  include HasPoster
  has_attached_file :poster, {
                    :styles => { :small => "200x112>", :medium => "300x168>", :thumb => "172x97>" },
                    :default_url => "/images/episode_default_image_:style.png",
                  }.merge(Tvshows::Application.config.paperclip_options)
  process_in_background :poster
  belongs_to :season
  has_one :series, :through => :season
  has_many :comments, :as => :commentable, :order => "created_at desc"
  has_many :activities, :dependent => :destroy, :as => :actor
  has_many :inv_activities, :class_name => "Activity", :dependent => :destroy, :as => :subject
  has_many :seens, :as => :seenable
  has_many :ratings, :as => :rateable
  
  attr_reader :poster_url
  after_save :attach_poster
  
  # scopes
  scope :available, :conditions => [ "first_aired <= ?", Date.today]
  scope :seen_by, lambda { |user|
                                    { 
                                      :joins => "LEFT OUTER JOIN seens ON seens.seenable_id = episodes.id AND seens.seenable_type = 'Episode'",
                                      :conditions => ["seens.user_id = ? AND seens.id IS NOT NULL", user.id] 
                                    } 
                                }
  scope :unseen_by, lambda { |user| { :joins => "LEFT OUTER JOIN seens ON seens.seenable_id = episodes.id AND seens.seenable_type = 'Episode' and seens.user_id = #{user.id}", :conditions => ["seens.id IS NULL"] } }

  # validations
  validates :name, :presence => true, :exclusion => { :in => %w(TBA tba) }
  validates :first_aired, :presence => true
  
  def self.find_by_show_id_and_season_number_and_episode_number(show_id, season_number, episode_number)
    Series.find(show_id).episodes.includes(:season).where("seasons.number" => season_number,
                                                       :number => episode_number).first
  end
  
  def attach_poster
    Delayed::Job.enqueue(AttachPosterToEpisodeJob.new(id, @poster_url), { :priority => 4 }) unless @poster_url.nil?
  end
  
  def poster_url=(value)
    @poster_url = value
    self.poster_processing = !value.blank?
  end
  
  def available?(date = Date.today)
    aired?(date) && updated_at.to_date >= first_aired # Time.at(Settings.last_update.to_i).to_date
  end
  
  def aired?(date = Date.today)
    first_aired <= date
  end
  
  def full_name
    @full_name ||= "#{series.name} S#{season.number.to_s.rjust(2, '0')}E#{number.to_s.rjust(2, '0')} - #{self.name}"
  end
  
  def short_name
    @short_name ||= "S#{season.number.to_s.rjust(2, '0')}E#{number.to_s.rjust(2, '0')} - #{self.name}"
  end
  
  def previous
    if @previous.nil?
      cur_index = series.episodes.find_index(self)
      @previous = series.episodes[cur_index - 1] unless cur_index.zero?
    end
    @previous
  end
  
  def next
    @next ||= series.episodes[series.episodes.find_index(self) + 1]
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_user!, :only => [:comment, :mark, :rate, :unmark]
  def show
    @episode = Episode.find_by_show_id_and_season_number_and_episode_number(params[:show_id],
               params[:season_number], params[:episode_number])
    @page_title = "#{@episode.series.full_name} S#{@episode.season.number.to_s.rjust(2, '0')}E#{@episode.number.to_s.rjust(2, '0')}"
    respond_to do |format|
      format.json { render :json => @episode }
      format.html
    end
  end
  
  def get_poster
    @episode = Episode.find(params[:id])
    respond_to do |format|
      format.js do
        if @episode.poster_processing?
          render :nothing => true, :status => 403
        else
          render :partial => "poster", :locals => { :episode => @episode }
        end
      end
      format.html { redirect_to episode_path(@episode) } # redirect to show
    end
  end
  
  def mark
    episode = Episode.find(params[:id])
    current_user.episodes_seen << episode
    respond_to do |format|
      format.js do
        render :partial => "shows/episode_check_my", :locals => { :episode => episode }
      end
      format.html { redirect_to show_season_episode_path_(episode) }
    end
  end
  
  def unmark
    episode = Episode.find(params[:id])
    current_user.episodes_seen.delete(episode)
    respond_to do |format|
      format.js do
        render :partial => "shows/episode_check_my", :locals => { :episode => episode }
      end
      format.html { redirect_to show_season_episode_path_(episode) }
    end
  end
  
  def comment
    if user_signed_in?
      @episode = Episode.find(params[:id])
      @comment = @episode.comments.build(:content => params[:comment][:content],
                                 :user => current_user)
      series = @episode.series
      season = @episode.season 
      save_comment(@comment)
      unless @comment.new_record?
        a_data = { "content" => @comment.content,
                   "commented_name" => @comment.commentable.full_name,
                   "commented_path" => show_season_episode_path_(@episode) }
        a = current_user.activities.create!(:actor_path => user_path(current_user),
                                            :actor_img => current_user.avatar_url(:thumb),
                                            :subject => @comment,
                                            :subject_path => show_season_episode_path_(@episode, :anchor => "comment-#{@comment.id}"),
                                            :kind => "comment",
                                            :data => a_data.to_json)
      end
    end
  end
  
  def rate
    @episode = Episode.find(params[:id])
    if params[:episode_rate].blank? || params[:episode_rate].to_i.zero?
      @episode.ratings.where(["user_id = ?", current_user.id]).destroy_all
      flash.now[:notice] = "Vote removed"
      respond_to do |format|
        format.js
        format.html { redirect_to episode_path(@episode), :notice => "Your rating has been removed successfully" } # redirect to show
      end
    elsif %w{ 1 2 3 4 5 }.include? params[:episode_rate]
      @episode.ratings.where(["user_id = ?", current_user.id]).destroy_all
      
      rating = @episode.ratings.build(:value => params[:episode_rate], :user => current_user)
      rating.save
      flash.now[:notice] = "Thanks for your vote"
      respond_to do |format|
        format.js
        format.html { redirect_to episode_path(@episode), :notice => "You have rated the episode successfully" } # redirect to show
      end
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def aired_on(air_day, air_time)
    if air_day.nil?
      return "The air date of this episode is not available ... yet."
    elsif air_day > Date.today
      sentence = "Will be aired on "
    elsif air_day == Date.today
      return sentence = "Airing today at #{air_time}"
    else
      sentence = "Aired on "
    end
    (sentence + (l air_day.to_date, :format => :dmy_with_long_month)).html_safe
  end
end

app/views/episodes/_poster.html.erb
<% if @episode.available? && @episode.poster_processing? %>
  <div class="processing" id="poster">
    <%= image_tag "ajax-loader-2-transparent.gif" %>
  </div>
<% else %>
  <div id="poster">
    <%= image_tag @episode.poster.url(:medium), :class => "thumbnail",
                  :class => "poster" %>
  </div>
<% end %>

app/views/episodes/_ratings.html.erb
<script type="text/javascript">
$(function(){
  $(".buttons form input[type=radio].rate").change(function(){
    $(this).closest('form').submit();
  }).rating();
  $(".star-rating-control .star-rating").click(function(){
    $("input#" + $(this).attr('id')).change();
  });
});
</script>
<% if user_signed_in? %>
  <%= form_tag rate_episode_path(episode), :remote => true, :style => "margin-right:5px", :id => "ratings_form" do %>
    <%= radio_button_tag("episode_rate", 0, current_user.rating_for(episode) == 0, :style => "display:none") %>
    <% 5.times do |i| %>
      <%= radio_button_tag("episode_rate", i + 1, current_user.rating_for(episode) == i + 1, :class => "rate") %>
    <% end %>
    <% if episode.ratings.count > 0 %>
    <span id="ratings">
      (<%= episode.ratings.inject(0){ |sum, e| sum + e.value }.to_f/episode.ratings.count %>/5 - <%= pluralize episode.ratings.count, 'rating' %>)
    </span>
    <% end %>
  <% end %>
<% else %>
  <% if episode.ratings.count > 0 %>
  <span id="ratings" style="">
    <%= episode.ratings.inject(0){ |sum, e| sum + e.value }.to_f/episode.ratings.count %>/5 - <%= pluralize episode.ratings.count, 'rating' %>
  </span>
  <% end %>
<% end %>

app/views/episodes/rate.js.erb
$("#ratings_form").replaceWith("<%= escape_javascript(render :partial => 'ratings', :locals => { :episode => @episode, :notice => @notice }) %>");
<% if flash.now[:notice] %>
	$("#ratings_form span#ratings").effect("highlight");
<% end %>

app/views/episodes/show.html.erb
<% content_for :html_tags do %>
 xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml"
<% end %>
<script>
  var posterIntervalID = null;
  var getPosterPath = "<%= get_poster_episode_path(@episode)%>";
  $(document).ready(function(){
    updateProcessingElements(posterIntervalID, "#poster.processing", getPosterPath);
    $(".buttons a").tipsy({gravity: 's'});
  });
</script>
<style>
  div.buttons { padding-top:0px; }
</style>
<div class="left_articles">
  <div class="buttons">
    <div style="margin-top:0px;width:400px">
      <%= render :partial => "ratings", :locals => { :episode => @episode } %>
	    <div id="comments_button" style="display:inline-block">
	      <%= link_to "Comments (#{@episode.comments.count})", :anchor => "comments" %>
	    </div>
      <% if @episode.previous %>
      <div id="prev_episode_button" style="display:inline-block">
      <%= link_to "Previous episode", show_season_episode_path_(@episode.previous), :title => @episode.previous.full_name %>
      </div>
      <% end %>
      <% if @episode.next %>
      <div id="next_episode_button" style="display:inline-block">
        <%= link_to "Next episode", show_season_episode_path_(@episode.next), :title => @episode.next.full_name %>
      </div>
      <% end %>
    </div>
  </div>
  <h2>
    <%= link_to "#{@episode.series.full_name}", show_path(@episode.series) %>
    <%= link_to "S#{@episode.season.number.to_s.rjust(2, "0")}", show_season_path(:season_number => @episode.season.number, :show_id => @episode.series) %><%= "E#{@episode.number.to_s.rjust(2, "0")}" %> - <%= @episode.name %>
  </h2>
	<p class="description"><%= aired_on(@episode.first_aired, @episode.series.air_time) %></p>
	<div id="episode-<%= @episode.id %>" class="episode_info">
  	<div>
      <%= render "poster" %>
      <% if @episode.available? %>
        <div>
          <% description = truncate(@episode.description, 795, "") %>
          <% if @episode.description.blank? %>
            <p style="padding-top:60px;text-align:center">The description is not available yet.</p>
          <% else %>
            <%= description %>
            <% if @episode.description.length > description.length %>
              <%= link_to_function("...", "showMoreDescription(this);") %>
              <span style="display:none">
                <%= @episode.description[(description.length)..-1] %>
              </span>
            <% end %>
          <% end %>
        </div>
        <%= facebook_like_button(show_season_episode_url_(@episode)) %>
        <% content_for :meta_tags do %>
          <meta property="og:title" content="<%= @episode.full_name %>" />
          <meta property="og:type" content="tv_show" />
          <meta property="og:url" content="<%= show_season_episode_url_(@episode) %>" />
          <meta property="og:image" content="<%= @episode.poster.url(:medium) %>" />
          <meta property="og:site_name" content="8PM.TV" />
          <meta property="fb:admins" content="663974483" />
        <% end %>
      <% end %>
  	</div>
  	<div class="clear"></div>
  </div>
</div>

<%= render :partial => "shared/comments", :locals => { :comment_path => comment_episode_path(@episode), :comments => @episode.comments }%>