config/routes.rb
Tvshows::Application.routes.draw do
  resources :authentications, :only => [:create, :destroy]

  devise_for :users, :path_names => { :sign_up => "register",
                                      :sign_in => "login",
                                      :sign_out => "logout" },
             :controllers => {
                                :registrations => 'registrations',
                                :sessions => 'sessions',
                                :omniauth_callbacks => "omniauth_callbacks"
                             } do
    
    get "users/cancel_omniauth", :to => "registrations#cancel_omniauth", :as => "cancel_omniauth"
    
    get "sessions/load_activities", :to => "sessions#load_activities"
    get "auth/failure", :to => "sessions#new", :as => "auth_failure"

    root :to => "sessions#index"
  end      

  resources :actors, :only => [:show]
  resources :seasons, :only => [:comment] do
    member do
      post  :comment
      get   :get_poster
      get   :mark
    end
  end
  resources :episodes, :only => [] do
    member do
      post :comment
      get  :get_poster
      get :mark
      get :unmark
      post :rate
    end
  end
  resources :shows, :only => [:index, :show] do
    resources :actors, :only => [:show, :index], :controller => "roles"
    collection do
      post :search
      get :search
      get :name
      get :popular
    end
    member do
      get :add  
      get :follow
      get :unfollow
      post :comment
      get :get_poster
      get :get_seasons
      get :get_next_episode
    end
    match "/season/:season_number" => "seasons#show", :constraints => { :season_number => /\d+/ }, :as => "season"
    match "/:season_number/:episode_number" => "episodes#show", :constraints => { :season_number => /\d+/, :episode_number => /\d+/ }, :as => "season_episode"
  end
  resources :genres, :only => [:show, :index]
  resources :users, :only => [:show, :index] do
    collection do
      get :name
    end
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :block
      get :unblock
    end
  end
  resources :comments, :only => [] do
    member do
      get :like
      get :unlike
      get :dislike
      get :undislike
    end
  end
  
  namespace "my" do
    resources :shows, :only => [:index, :show]
  end
  
  match '/robots.txt', :controller => :application, :action => :robots

  root :to => "sessions#index"

end

app/controllers/my/shows_controller.rb
class My::ShowsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @shows = current_user.series.order("name ASC") if current_user
  end
  
  def show
    @show = Series.find(params[:id])
    @unseen_episodes = @show.episodes.available.unseen_by(current_user)
    @next_episode = @show.next_episode
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  require 'net/http'
  
  before_filter :authenticate_user!, :only => [ :my, :subscribe, :unsubscribe ]
  
  public
  
  def index
    name_alpha
    render :action => :name
  end
  
  def search
    if request.xhr?
      results = { :query => params[:query], :suggestions => [], :data => [] }
      query = params[:query].downcase.strip
      unless query.starts_with?("the ")
        series = Series.where("lower(name) LIKE :name OR lower(name_prefix) LIKE :name", { :name => "%#{query}%"} ).all
      else
        series = Series.where("(lower(name_prefix) = 'the' AND lower(name) LIKE :name_sub) OR (lower(name) LIKE :name)", { :name => "%#{query}%", :name_sub => "%#{query.gsub(/^the\s/, '')}%"} ).all
      end
      series.each do |serie|
        results[:suggestions] << serie.full_name
        results[:data] << { :id => serie.id, :param => serie.to_param } 
      end
      results[:suggestions] << "#{params[:query]}"
      results[:data] << { :param => "search?q=#{params[:query]}"}
      render :json => results.to_json
    else
      tvdb = TvdbParty::Search.new(Tvshows::Application.config.the_tv_db_api_key)
      results = tvdb.search(params[:q])
      db_series = Series.where("lower(name) LIKE lower(:name)", { :name => "%#{params[:q]}%" }).all
      @series = []
      
      
      respond_to do |format|
        format.html do
          results.each do |s|
            unless s["Overview"].blank?
              db_serie = db_series.detect { |ds| ds.series_id == s["seriesid"].to_i }
              if db_serie.nil?
                s["Link"] = add_show_path(s["seriesid"])
                s["Saved"] = false
              else
                s["Link"] = show_path(db_serie)
                s["Saved"] = true
              end
              @series << s
            end
          end
          redirect_to @series.first["Link"] if @series.size == 1 && @series.first["Saved"]
        end #search.html.erb
        format.json do
          results.each do |s|
            unless s["Overview"].blank?
              db_serie = db_series.detect { |ds| ds.series_id == s["seriesid"].to_i }
              s["Link"] = db_serie.nil? ? add_show_path(s["seriesid"], :format => :json) : show_path(db_serie, :format => :json)
              @series << s
            end
          end 
          render :json => @series
        end
      end
    end
  end
  
  def show
    @series = Series.find(params[:id])

    if user_signed_in?
      # A logged user can comment
      @comment = Comment.new
      
      # If the user is watching this show
      if current_user.watch?(@series)
        # Get the next episode unseen
        @unseen_episodes = @series.episodes.available.unseen_by(current_user)
        @next_episode_unseen = @unseen_episodes.first

        # Display the activity tab
        if params[:tab].nil?
          redirect_to show_path(@series, :tab => "activity")
          return
        end
      end
    end

    @page_title = @series.full_name
    respond_to do |format|
      format.json { render :json => @series.as_json }
      format.html
    end
  end
  
  def add
    series = Series.where(:series_id => params[:id]).first
    if series.nil?
      tvdb = TvdbParty::Search.new(Tvshows::Application.config.the_tv_db_api_key)
      s = tvdb.get_series_by_id(params[:id])
      series = Series.new(:name => s.name, :series_id => s.id,
                          :tvdb_id => s.tvdb_id, :description => s.overview,
                          :first_aired => s.first_aired, :network => s.network,
                          :rating => s.rating, :runtime => s.runtime,
                          :status => s.status == "Continuing",
                          :imdb_id => s.imdb_id,
                          :rating_count => s.rating_count,
                          :air_time => s.air_time, :air_day => s.air_day,
                          :seasons_processing => true, :poster_url => s.poster)
      s.genres.each { |genre| series.genres << Genre.find_or_initialize_by_name(genre) }
      if !series.save
        redirect_to root_url, :notice => "Sorry, there was a problem saving the TV show #{series.full_name}. Try again later."
        return
      end
    end
    
    redirect_to show_path(series)
  end
  
  def follow
    @series = Series.find(params[:id])
    if current_user.following?(@series)
      respond_to do |format|
        format.js   # render follow.js.erb
        format.html { redirect_to show_path(@series) }
      end
    else
      fw = current_user.follow(@series)
      a = current_user.activities.create!(:actor_path => user_path(current_user),
                                          :actor_img => current_user.avatar_url(:thumb),
                                          :subject => fw,
                                          :kind => "follow_serie",
                                          :data => { "serie_path" => show_path(@series),
                                                    "serie_name" => @series.full_name,
                                                    "serie_img" => @series.poster.url(:thumb),
                                                    "serie_desc" => @series.description }.to_json)
      respond_to do |format|
        format.js   # render follow.js.erb
        format.html { redirect_to show_path(@series), :notice => "You are now following #{@series.full_name}" }
      end
    end
  end
  
  def unfollow
    @series = Series.find(params[:id])
    if current_user.following?(@series)
      current_user.stop_following(@series)
      respond_to do |format|
        format.js   # render unsubscribe.js.erb
        format.html { redirect_to show_path(@series), :notice => "You are not following #{@series.name} anymore." }
      end
    else
      respond_to do |format|
        format.js   # render unsubscribe.js.erb
        format.html { redirect_to show_path(@series) }
      end
    end
  end
  
  def actors
  end
  
  def comment
    if user_signed_in?
      @series = Series.find(params[:id])
      @comment = @series.comments.build(:content => params[:comment][:content],
                                 :user => current_user) 
      save_comment(@comment)
      a = current_user.activities.create!(:actor_path => user_path(current_user),
                                          :actor_img => current_user.avatar_url(:thumb),
                                          :subject => @comment,
                                          :subject_path => show_path(@series, :anchor => "comment-#{@comment.id}"),
                                          :kind => "comment",
                                          :data => { "content" => @comment.content,
                                                    "commented_name" => @comment.commentable.full_name,
                                                    "commented_path" => show_path(@series) }.to_json)
    end
  end
  
  def name
    name_alpha
  end
  
  def get_poster
    @series = Series.find(params[:id])
    respond_to do |format|
      format.js do
        if @series.poster_processing?
          render :nothing => true, :status => 403
        else
          render :partial => "poster", :locals => { :series => @series }
        end
      end
      format.html { redirect_to show_path(@series) } # redirect to show
    end
  end
  
  def popular
  end
  
  def get_seasons
    @series = Series.find(params[:id])
    respond_to do |format|
      format.js do
        if @series.seasons_processing?
          render :nothing => true, :status => 403
        else
          render :partial => "seasons", :locals => { :series => @series.seasons }
        end
      end
      format.html { redirect_to show_path(@series) } # redirect to show
    end
  end
  
  def genres
    @genres = Genre
  end
  
  def get_next_episode
    series = Series.find(params[:id])
    if current_user.watch?(series)
      # Get the next episode unseen
      unseen_episodes = series.episodes.available.unseen_by(current_user)
      @next_episode_unseen = unseen_episodes.first

      respond_to do |format|
        format.js { render :partial => "shows/next_episode_my" }
      end
    end
  end
  
  private
  def name_alpha
    if params[:letter].nil?
      @series = Series.where("name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? \
                              OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ? OR name LIKE ?",
                              "0%", "1%", "2%", "3%", "4%", "5%", "6%", "7%", "8%", "9%")
    elsif ('A'..'Z').include?(params[:letter])
      @series = Series.where("name LIKE ?", "#{params[:letter]}%").order("name asc")
    else
      @series = []
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper

  def az_shows_initials(current_letter)
    content = ""
    ('A'..'Z').each do |l|
      content << "<li"
      content << " class=\"selected\"" if current_letter == l
      content << ">" + (link_to l, name_shows_path(:letter => l)) + '</li>'
    end
    
    content.html_safe
  end
  
  def people_watching(serie)
    people_watching = serie.watchers.all
    
    if people_watching.size.zero?
      desc = "Nobody is watching this TV show"
    elsif user_signed_in?
      watchers = []
    
      # Put the current user in the watchers list if he watches the serie
      if people_watching.include?(current_user) 
        watchers << "You"
        people_watching = people_watching - [current_user]
      end
      
      followings_watching = current_user.followings_watching(serie)
      
      # Do not display more than 3 friends in the description
      if followings_watching.size > 3
        # If there are more than 3 friends put a number of friends !
        watchers << "#{followings_watching.size} of your friends"
      else
        # Otherwise, lists the friends
        followings_watching.each { |f| watchers << link_to(f.username, user_path(f)) ; people_watching.delete(f) } unless followings_watching.size.zero?
      end

      # Remove friends from anonymous people
      people_watching = people_watching - followings_watching
      
      # Finally, put the rest of the watchers (anonymous)
      if watchers.size.zero?
        watchers << "#{pluralize(people_watching.size, 'person is', 'people are')}"
        desc = "#{watchers.to_sentence} watching this show"
      else
        watchers << "#{pluralize(people_watching.size, 'other person', 'other people')}" unless people_watching.size.zero?
        desc = "#{watchers.to_sentence} " + (serie.watchers.size == 1 && serie.watchers.first != current_user ? "is" : "are") + " watching this show"
      end
    else
      desc = "#{pluralize(people_watching.size, 'person is', 'people are')} watching this TV show"
    end
    desc.html_safe
  end
  
  def people_watching_except_you(serie)
    people_watching = serie.watchers.all.reject{|u| u == current_user}
    if people_watching.size.zero?
      desc = "Nobody else is watching this TV show"
    elsif user_signed_in?
      watchers = []
      
      followings_watching = current_user.followings_watching(serie)
      
      # Do not display more than 3 friends in the description
      if followings_watching.size > 3
        # If there are more than 3 friends put a number of friends !
        watchers << "#{followings_watching.size} of your friends"
      else
        # Otherwise, lists the friends
        followings_watching.each { |f| watchers << link_to(f.username, user_path(f)) ; people_watching.delete(f) } unless followings_watching.size.zero?
      end

      # Remove friends from anonymous people
      people_watching = people_watching - followings_watching
      
      # Finally, put the rest of the watchers (anonymous)
      if watchers.size.zero?
        watchers << "#{pluralize(people_watching.size, 'person is', 'people are')}"
        desc = "#{watchers.to_sentence} watching this show"
      else
        watchers << "#{pluralize(people_watching.size, 'other person', 'other people')}" unless people_watching.size.zero?
        desc = "#{watchers.to_sentence} " + (serie.watchers.reject{|w| w == current_user}.size == 1 ? "is" : "are") + " watching this show"
      end
    else
      desc = "#{pluralize(people_watching.size, 'person is', 'people are')} watching this TV show"
    end
    desc.html_safe
  end
  
  def watch_button(series)
    if user_signed_in?
      if current_user.watch?(series)
        link_to "Unfollow", unfollow_show_path(series), :class => "rm-movie-icon"
      else
        link_to "Follow", follow_show_path(series), :class => "add-movie-icon"
      end
    else
      "&nbsp;".html_safe
    end
  end
end

app/views/shows/_episode_check_my.html.erb
<% if current_user.has_watched?(episode) %>
<%= link_to image_tag("ajax-loader-circle-ball.gif", :style => "display:none"), unmark_episode_path(episode), :remote => true, 'data-type' => 'txt', :class => "check_box check_box_checked check_episode", :id => "check_episode_#{episode.id}" %>
<% else %>
<%= link_to image_tag("ajax-loader-circle-ball.gif", :style => "display:none"), mark_episode_path(episode), :remote => true, 'data-type' => 'txt', :class => "check_box check_box_empty check_episode", :id => "check_episode_#{episode.id}" %>
<% end %>

app/views/shows/_episodes.html.erb
<div id="series_activity" class="switchable">
  <% if user_signed_in? %>
    <%= render "next_episode_my" %>
  <% else %>
    
  <% end %>
  <div id="my_episodes">
    <%= render :partial => "shows/season_my", :collection => @series.seasons %>
  </div>
</div>

app/views/shows/_next_episode_my.html.erb
<div id="next_episode" style="border:1px solid #DEDEDE;padding:20px">
  <% if @next_episode_unseen.nil? %>
  <p style="font-weight:bold;text-align:center">You're up-to-date!</p>
  <% else %>
    <% episode = @next_episode_unseen %>
    <div class="episode-title">
      <div class="name">
        <span style="font-weight:bold;">Next episode: </span>
      </div>
    </div>

    <div>
      <%= link_to (image_tag episode.poster.url(:small), :class => "thumbnail description-added"), show_season_episode_path_(episode) %>
      <%= link_to episode.full_name, show_season_episode_path_(episode), :class => "episode-title" %>
    </div>
    <div class="air-time"><%= l episode.first_aired, :format => :dmy_with_long_month %></div>
    <div class="clear"></div>
  <% end %>
</div>

app/views/shows/_poster.html.erb
<% if @series.poster_processing? %>
  <div class="processing" id="poster">
    <%= image_tag "ajax-loader-2.gif" %>
  </div>
<% else %>
  <div id="poster">
    <%= image_tag @series.poster.url(:small), :class => "thumbnail",
                  :class => "poster" %>
  </div>
<% end %>

app/views/shows/_season_check_my.html.erb
<% if current_user.has_watched?(season) %>
<%= link_to_function image_tag("ajax-loader-circle-ball.gif", :style => "display:none"), "return false;", :class => "check_box check_box_checked check_season", :id => "check_season_#{season.id}", :style => "cursor:default" %>
<% else %>
<%= link_to image_tag("ajax-loader-circle-ball.gif", :style => "display:none"), mark_season_path(season), :remote => true, 'data-type' => 'txt', :class => "check_box check_box_empty check_season", :id => "check_season_#{season.id}" %>
<% end %>

app/views/shows/_season_my.html.erb
<% 
  season = season_my if season.nil?
  season_seen = current_user.has_watched?(season) if user_signed_in?
%>
<% unless season.episodes.size.zero? %>
  <div id="season_<%= season.number %>" class="season-info">
    <div class="season-title">
      <div class="name">
        <% if user_signed_in? %>
        <%= render :partial => "shows/season_check_my", :locals => { :season => season } %> &nbsp;
        <% end %>
        <%= link_to "Season #{season.number}", "#", :class => "season-link" %>
      </div>
    </div>
    <div class="season-episodes slidable" style="display:none;">
        <% for episode in season.episodes %>
        <div id="my_episode_<%= episode.id %>" class="my-episode my-episode-<%= cycle 'even', 'odd' %>">
          <div class="episode-title">
            <div class="name">
              <% if user_signed_in? %>
              <%= render :partial => "shows/episode_check_my", :locals => { :episode => episode } %>&nbsp;
              <% end %>
              <%= link_to episode.full_name, show_season_episode_path_(episode), :class => "episode-link" %>
            </div>
            <div class="air-time"><%= l episode.first_aired, :format => :dmy_with_long_month %></div>
            <div class="clear"></div>
          </div>

          <div style="display:none;margin:10px 0px" class="slidable">
            <%= link_to (image_tag episode.poster.url(:small), :class => "thumbnail description-added"), show_season_episode_path_(episode) %>
            <%= link_to episode.name, show_season_episode_path_(episode), :class => "episode-title" %>
            <div>
              <% if user_signed_in? && !current_user.has_watched?(episode) %>
                <span id="episode-<%= episode.id %>-description" style="display:none">
                  <%= episode.description %>
                </span>
                <p style="text-align:center">
                  <%= link_to_function "Show description", "$('#episode-#{episode.id}-description').show();$(this).hide();" %>
                </p>
              <% else %>
                <span id="episode-<%= episode.id %>-description">
                  <%= episode.description %>
                </span>
              <% end %>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/shows/_seasons.html.erb
<% if @series.seasons_processing? %>
  <div id="series_seasons" class="processing switchable">
    <p id="seasons_loading" class="seasons-loading" style="text-align:center">
      <span>Loading seasons ...</span><br />
      <%= image_tag("ajax-loader-bar.gif") %>
    </p>
  </div>
<% else %>
  <div id="series_seasons" style="overflow:overflow-y" class="switchable">
    <% unless @series.seasons.size.zero? %>
      <%= render :partial => "season", :collection => @series.seasons %>
      <div class="clear"></div>
    <% end %>
  </div>
<% end %>

app/views/shows/_series_categories.html.erb
<div id="series_categories">
  <p style="text-align:center">
    <% if user_signed_in? -%>
    <%= link_to("My series", my_shows_path)  %>&nbsp;&middot;&nbsp;
    <% end -%>
    <%= link_to "Name", name_shows_path %>&nbsp;&middot;&nbsp;<%= link_to "Genre", genres_path %>
  </p>
</div>

app/views/shows/follow.js.erb
$("p.description").html('<%= escape_javascript(people_watching(@series)) %>');
$("#watch_button").html('<%= escape_javascript(watch_button(@series)) %>').closest('p').effect("highlight", {}, 1000);;

app/views/shows/index.html.erb
<%= render "series_categories" %>

<% if @series.size > 0 %>
<div id="series_found">
  <h3><%= (t '.series_letter') %> <%= params[:letter] %> - <%= @series.size %> series <%= t '.found' %></h3>
  <ul>
  <% @series.each do |serie| %>
    <li>
      <div>
        <div class="series_poster">
          <%= link_to (image_tag serie.poster.url(:small)), show_path(serie) %>
        </div>
        <p><%= link_to serie.full_name, show_path(serie) %></p>
      </div>
    </li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shows/name.html.erb
<%= render "series_categories" %>
<div id="series_initials">
  <ul id="navlist">
    <% if params[:letter] %>
      <li class="first">
    <% else %>
      <li class="first selected">
    <% end %>
    <%= link_to "#", name_shows_path %></li>
    <%= az_shows_initials(params[:letter]) %>
  </ul>
</div>
<div id="series-list-name">
  <%= render :partial => "series_list", :locals => { :series => @series } %>
</div>

app/views/shows/search.html.erb
<h1>Here is what I found for "<%= params[:q] %>":</h1>

<div class="left_articles">
	<% for serie in @series %>
	<div id="series_info">
	  <h2><%= link_to serie["SeriesName"], serie["Link"] %></h2>
  	<p class="description">&nbsp;</p>
  	<p>
      <div>
        <% description = truncate(serie["Overview"], 795, "") %>
        <%= description %>
        <% if serie["Overview"].length > description.length %>
          <%= link_to_function("...", "showMoreDescription(this);") %>
          <span style="display:none">
            <%= serie["Overview"][(description.length)..-1] %>
          </span>
        <% end %>
      </div>
  	</p>
  	<div style="clear:both"></div>
  </div>
  <% end %>
</div>

app/views/shows/show.html.erb
<script type="text/javascript">
  function toggleLoading(from)
  {
    $("#ajax-loader").toggle();
  }
  var getSeasonsPath = "<%= get_seasons_show_path(@series) %>";
  var getPosterPath = "<%= get_poster_show_path(@series) %>";
  var getNextEpisodePath = "<%= get_next_episode_show_path(@series) %>";
  
  var posterIntervalID = null;
  var seasonsIntervalID = null;
    
  $(function(){
    updateProcessingElements(posterIntervalID, "#poster.processing", getPosterPath);
    updateProcessingElements(seasonsIntervalID, "#series_seasons.processing", getSeasonsPath);   

    var tab = $.getUrlVar('tab');

    var switchables = $(".switchable");

    if (tab !== "activity")
      switchables.not(":first").hide();
    else
    {
      switchables.not(":eq(1)").hide();

      var switcher = $('.switcher');
      var lis = switcher.find('li');

      lis.removeClass('selected');
      lis.eq(2).addClass('selected');
    }

    $(".switcher li a").click(function(){
      var switcher = $(this).parent('.switcher');
      var li = $(this).parent('li');
      
      li.siblings().removeClass('selected');
      li.addClass('selected');
      $('.switchable').hide();
      $('#' + $(this).attr('rel')).show();

      return false;
    })
    
    $("a.check_box").live("ajax:before", function(){
      $(this).children('img').show();
    })
    .live("ajax:complete", function(){
      $(this).children('img').hide();
    });
    
    
    $("a.check_season").live("ajax:success", function(jqXHR, data, textStatus){
      $(this).closest('div.season-info').replaceWith(data);
      updateNextEpisode();
    });
    
    $("a.check_episode").live("ajax:success", function(jqXHR, data, textStatus){
      $(this).replaceWith(data);
      updateNextEpisode();
    });
    
    function updateNextEpisode(){
      $.ajax({
        url:getNextEpisodePath,
        success:function(data){
          $("#next_episode").fadeOut(200, function(){
            $(this).replaceWith(data);
          });
        }
      });
    }
    $("a.season-link,a.episode-link").live('click', function(){
      $(this).closest('div.name').parent().siblings('div.slidable').slideToggle();
      return false;
    });
  });
</script>

<div class="left_articles">
  <div class="buttons">
	  <p>
	    <span id="comments_button">
	      <%= link_to "Comments (#{@series.comments.count})", :anchor => "comments" %>
	    </span>
	    <span id="watch_button"><%= watch_button(@series) %></span>
	  </p>
	</div>
  <h2><%= @series.full_name %></h2>
	<p class="description"><%= people_watching(@series) %></p>
	<div id="series-<%= @series.id %>" class="series_info">
      <%= render "poster" %>
      <div id="series_details">
        <div id="series_description">
          <% description = truncate(@series.description, 795, "") %>
          <%= description %>
          <% if !@series.description.blank? && @series.description.length > description.length %>
            <%= link_to_function("...", "showMoreDescription(this);") %>
            <span style="display:none">
              <%= @series.description[(description.length)..-1] %>
            </span>
          <% end %>
          <div class="air-time" style="margin-top:20px">
            <span class="label"><%= t '.air_time'%>:</span>
            <%= @series.air_day %> <%= t '.at' %>
            <%= @series.air_time %> (<%= @series.runtime %> mn)
          </div>
          <div class="genre" style="margin-top:20px">
            <span class="label">Genres:</span>
            <% for genre in @series.genres %>
              <%= link_to genre.name, genre %>&nbsp;
            <% end %>
          </div>
        </div>
  	  </div>
  	<div class="clear"></div>
  </div>
</div>

<div class="switcher">
  <ul>
    <li><%= link_to "Seasons (#{@series.seasons.size})", "#", :rel => "series_seasons" %></li>
    <li><%= link_to "Comments (#{@series.comments.size})", "#", :rel => "series_comments" %></li>
    <li><%= link_to "Episode Guide (#{@series.aired_episodes.size})", "#", :rel => "series_activity" %></li>
  </ul>
</div>

<!-- Switchables -->
<!-- Seasons -->
<%= render "seasons" %>

<!-- Comments -->
<a name="comments"></a>

<!-- Episodes -->
<%= render "episodes" %>

<%= render :partial => "shared/comments", :locals => { :comment_path => comment_show_path(@series), :comments => @series.comments, :klass => "switchable" } %>

app/views/shows/unfollow.js.erb
$("p.description").html('<%= escape_javascript(people_watching(@series)) %>');
$("#watch_button").html('<%= escape_javascript(watch_button(@series)) %>').closest('p').effect("highlight", {}, 1000);;